/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Classes.Cliente;
import Classes.Conta;
import Classes.ContaCorrenteComum;
import Classes.ContaCorrenteLimitada;
import Classes.ContaPoupanca;
import Classes.Deposito;
import Classes.Extrato;
import java.io.FileNotFoundException;
import static java.lang.System.exit;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author fabio
 */
public class TelaDeposito extends javax.swing.JFrame {
    Extrato ex = new Extrato();
    
    public void foco() {
        if (varAgencia.isEnabled()) {
            varAgencia.requestFocus();
        } else if (varConta.isEnabled()) {
            varConta.requestFocus();
        } else if (varValor.isEnabled()) {
            varValor.requestFocus();
        } else if(varTelefone.isEnabled()) {
            varTelefone.requestFocus();
        }
    }

    public void voltar() {
        if (!varAgencia.isEnabled() && varConta.isEnabled()) {
            varConta.setEnabled(false);
            varAgencia.setEnabled(true);
            foco();
        } else if (!varAgencia.isEnabled() && !varConta.isEnabled() && varValor.isEnabled()) {
            varConta.setEnabled(true);
            varValor.setEnabled(false);
            foco();
        }else if(!varAgencia.isEnabled() && !varConta.isEnabled() && !varValor.isEnabled() && varTelefone.isEnabled()) {
            varValor.setEnabled(true);
            varTelefone.setEnabled(false);
            foco();
        }else if(!varAgencia.isEnabled() && !varConta.isEnabled() && !varValor.isEnabled() && varTelefone.isEnabled()) {
            varTelefone.setEnabled(false);
            varValor.setEnabled(true);
            varConta.setEnabled(false);
            varAgencia.setEnabled(false);
        
        }
    }

    public void corrige() {
        if (varAgencia.isEnabled() == true) {
            varAgencia.setText("");
            varAgencia.requestFocus();
        } else if (varConta.isEnabled() == true) {
            varConta.setText("");
            varConta.requestFocus();
        }else if(varValor.isEnabled() == true) {
            varValor.setText("");
            varValor.requestFocus();
        }else if(varTelefone.isEnabled() == true) {
            varTelefone.setText("");
            varTelefone.requestFocus();
        }
    }

    /**
     * Creates new form TelaDeposito
     */
    public TelaDeposito() {
        initComponents();
        varConta.setEnabled(false);
        varTelefone.setEnabled(false);
        varValor.setEnabled(false);
        varAgencia.requestFocus();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnPoupanca = new javax.swing.JRadioButton();
        btnCorrenteComum = new javax.swing.JRadioButton();
        varAgencia = new javax.swing.JTextField();
        varConta = new javax.swing.JTextField();
        varValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnConfirma = new javax.swing.JButton();
        btnCorrige = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        varTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCorrenteLimitada = new javax.swing.JRadioButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        btnPoupanca.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup1.add(btnPoupanca);
        btnPoupanca.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnPoupanca.setForeground(new java.awt.Color(254, 254, 254));
        btnPoupanca.setText("Poupança");
        btnPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoupancaActionPerformed(evt);
            }
        });

        btnCorrenteComum.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup1.add(btnCorrenteComum);
        btnCorrenteComum.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCorrenteComum.setForeground(new java.awt.Color(254, 254, 254));
        btnCorrenteComum.setText("Corrente Comum");
        btnCorrenteComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrenteComumActionPerformed(evt);
            }
        });

        varAgencia.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        varAgencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                varAgenciaKeyTyped(evt);
            }
        });

        varConta.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        varValor.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setText("Agência");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Conta");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 254, 254));
        jLabel3.setText("Valor");

        btnConfirma.setBackground(new java.awt.Color(0, 51, 153));
        btnConfirma.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnConfirma.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirma.setText("Confirma");
        btnConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaActionPerformed(evt);
            }
        });

        btnCorrige.setBackground(new java.awt.Color(0, 51, 153));
        btnCorrige.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCorrige.setForeground(new java.awt.Color(255, 255, 255));
        btnCorrige.setText("Corrige");
        btnCorrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrigeActionPerformed(evt);
            }
        });

        btnCancela.setBackground(new java.awt.Color(0, 51, 153));
        btnCancela.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCancela.setForeground(new java.awt.Color(255, 255, 255));
        btnCancela.setText("Cancela");

        varTelefone.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("Telefone");

        btnCorrenteLimitada.setBackground(new java.awt.Color(204, 204, 0));
        buttonGroup1.add(btnCorrenteLimitada);
        btnCorrenteLimitada.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCorrenteLimitada.setForeground(new java.awt.Color(254, 254, 254));
        btnCorrenteLimitada.setText("Corrente Limitada");
        btnCorrenteLimitada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrenteLimitadaActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(0, 51, 153));
        btnVoltar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(btnCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnCorrenteLimitada)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(varAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(varConta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(varValor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(jLabel1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(31, 31, 31)
                                            .addComponent(jLabel2))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(36, 36, 36)
                                            .addComponent(jLabel3))
                                        .addComponent(varTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPoupanca)
                                .addGap(61, 61, 61)
                                .addComponent(btnCorrenteComum)))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPoupanca)
                    .addComponent(btnCorrenteComum)
                    .addComponent(btnCorrenteLimitada))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(varAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(varConta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(varValor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(varTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoupancaActionPerformed
        foco();
    }//GEN-LAST:event_btnPoupancaActionPerformed

    private void btnConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaActionPerformed
        foco();
        if (varAgencia.isEnabled() == true && !varAgencia.getText().isEmpty()) {
            varAgencia.setEnabled(false);
            varConta.setEnabled(true);
            varConta.requestFocus();
            varTelefone.setEnabled(false);
            varValor.setEnabled(false);
           
        } else if (varConta.isEnabled() == true && !varConta.getText().isEmpty()) {
            varConta.setEnabled(false);
            varValor.setEnabled(true);
            varTelefone.setEnabled(false);
            varValor.requestFocus();
            foco();
        } else if (varValor.isEnabled() == true && !varValor.getText().isEmpty()) {
            varValor.setEnabled(false);
            varTelefone.setEnabled(true);
            varTelefone.requestFocus();
            foco();
        } else if (varTelefone.isEnabled() == true && !varTelefone.getText().isEmpty()) {
            varAgencia.setEnabled(false);
            varConta.setEnabled(false);
            varValor.setEnabled(false);
            
            

            if (btnPoupanca.isSelected()) {
                Deposito dep;
                String txt;
                //Conta.visualizarArquivos(varConta.getText());
                double vl = Double.valueOf(varValor.getText());
                ContaPoupanca cp = new ContaPoupanca();
                cp = ContaPoupanca.Leitura(varConta.getText());
                if (cp.getTipo().equalsIgnoreCase("poupança")) {
                    Conta.visualizarArquivos(varConta.getText());
                    int opt = JOptionPane.showConfirmDialog(null, cp.getCli().getNome() + "\n"
                            + varValor.getText(), null, WIDTH);
                    if (opt == JOptionPane.YES_OPTION) {
                        dep = new Deposito(varConta.getText(), varAgencia.getText(), vl, varTelefone.getText());
                        dep.deposita(dep, cp);
                        txt = "Valor depositado: " + varValor.getText() + "\nTelefone para Contato: " + varTelefone.getText() + "\n";
                        ex.gravaLog(varConta.getText(), txt);
                        this.dispose();
                        new TelaCaixa().setVisible(true);
                    } else if (opt == JOptionPane.NO_OPTION) {

                    }
                }
            } else if (btnCorrenteComum.isSelected()) {
                String txt;
                Deposito dep;
                double vl = Double.valueOf(varValor.getText());
                ContaCorrenteComum ccc = new ContaCorrenteComum();
                ccc = ContaCorrenteComum.Leitura(varConta.getText());
                if (ccc.getTipo().equalsIgnoreCase("Corrente Comum")) {
                    int opt = JOptionPane.showConfirmDialog(null, ccc.getCli().getNome() + "\n"
                            + varValor.getText(), null, WIDTH);
                    if (opt == JOptionPane.YES_OPTION) {
                        dep = new Deposito(varConta.getText(), varAgencia.getText(), vl, varTelefone.getText());
                        dep.deposita(dep, ccc);
                        txt = "Valor depositado: " + varValor.getText() + "\nTelefone para Contato: " + varTelefone.getText() + "\n";
                        ex.gravaLog(varConta.getText(), txt);
                        this.dispose();
                        new TelaCaixa().setVisible(true);
                    }
                }
            } else if (btnCorrenteLimitada.isSelected()) {
              
                String txt = "";
                Deposito dep;
                double vl = Double.valueOf(varValor.getText());
                ContaCorrenteLimitada ccl = new ContaCorrenteLimitada();
                ccl = ContaCorrenteLimitada.Leitura(varConta.getText());
                if (ccl.getTipo().equalsIgnoreCase("Corrente Limitada")) {
                    int opt = JOptionPane.showConfirmDialog(null, ccl.getCli().getNome() + "\n"
                            + varValor.getText(), null, WIDTH);
                    if (opt == JOptionPane.YES_OPTION) {
                        dep = new Deposito(varConta.getText(), varAgencia.getText(), vl, varTelefone.getText());
                        dep.deposita(dep, ccl);
                        txt = "Valor depositado: " + varValor.getText() + "\nTelefone para Contato: " + varTelefone.getText() + "\n";
                        ex.gravaLog(varConta.getText(), txt);
                        this.dispose();
                        new TelaCaixa().setVisible(true);
                    }
                }
                
            }else{
                JOptionPane.showMessageDialog(null,"Selecione um Tipo de Conta!!!", "", ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnConfirmaActionPerformed

    private void btnCorrenteLimitadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrenteLimitadaActionPerformed
        foco();
    }//GEN-LAST:event_btnCorrenteLimitadaActionPerformed

    private void btnCorrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrigeActionPerformed
        corrige();
    }//GEN-LAST:event_btnCorrigeActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        foco();
        voltar();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCorrenteComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrenteComumActionPerformed
        foco();
    }//GEN-LAST:event_btnCorrenteComumActionPerformed

    private void varAgenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varAgenciaKeyTyped
        if(varAgencia.getText().length() == 3) {
            btnConfirma.doClick();
        }
    }//GEN-LAST:event_varAgenciaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnConfirma;
    private javax.swing.JRadioButton btnCorrenteComum;
    private javax.swing.JRadioButton btnCorrenteLimitada;
    private javax.swing.JButton btnCorrige;
    private javax.swing.JRadioButton btnPoupanca;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField varAgencia;
    private javax.swing.JTextField varConta;
    private javax.swing.JTextField varTelefone;
    private javax.swing.JTextField varValor;
    // End of variables declaration//GEN-END:variables
}
